website/farming/urls.py
from django.conf.urls import url
from . import views

from django.contrib.auth import views as auth_views
from django.urls import path


app_name = 'farming'

urlpatterns=[

    url(r'^$' , views.home , name='home'),
    url(r'^display_info$' , views.display_info , name='display_info'),
    url(r'^register$' , views.register , name='register'),

    path('login/', auth_views.LoginView.as_view(), name='login1'),
    url(r'^check_new$' , views.check_new , name='check_new'),
    url(r'^del_pics$' , views.delete_pics , name='delete_pics'),
    url(r'^check_new2$' , views.check_new2 , name='check_new2'),
    url(r'^check_old$' , views.check_old , name='check_old'),
    url(r'^about$' , views.about , name='about'),
    url(r'^logout$' , views.logout_view , name='logout_view'),
]

website/website/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from farming import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/',admin.site.urls),
    url(r'^', include('farming.urls')),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)       

website/farming/models.py
from django.db import models
from django.contrib.auth.models import Permission, User
# Create your models here.


class Person(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email=models.EmailField(max_length=100,primary_key=True)
    address=models.CharField(max_length=255)
    age=models.IntegerField()
    GENDER_CHOICES = (
        (0, 'male'),
        (1, 'female'),
        (2, 'not specified'),
    )
    gender = models.IntegerField(choices=GENDER_CHOICES)
    profession=models.CharField(max_length=255)

    
class photo_data(models.Model):
    email1=models.CharField(max_length=255)
    disease = models.CharField(max_length=255)
    suggestion = models.CharField(max_length=1000)
    photo = models.ImageField(upload_to='photo_datas')
    

website/farming/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Person,photo_data


class RegistrationFormUser(forms.ModelForm):
    password = forms.CharField(max_length=32, widget=forms.PasswordInput)
    class Meta:
        model = Person
        fields = ['name', 'email', 'address','age', 'gender','password','profession']


class image_data(forms.ModelForm):
    class Meta:
        model = photo_data
        fields = ['photo']

website/farming/views.py
import runpy
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login , get_user_model
from .models import *
from django.db.models import Q
from django.contrib.messages import warning
from django.shortcuts import get_object_or_404
from .forms import RegistrationFormUser , image_data
import uuid,os,shutil
from PIL import Image
from farming import sn
from django.contrib.auth import logout




def logout_view(request):
    logout(request)
    # Redirect to a success page.
    return render(request,'home.html',{})




def home(request):
    return render(request,'home.html',{})


def display_info(request):

    user_info=Person.objects.filter(user=request.user)
    print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$88",user_info)
    return render(request, 'display_info.html', {'details':user_info,'name':user_info.values()[0]['name']})
    

def login1(request):
    if request.method == "POST":
        email = request.POST['username']
        password = request.POST['password']
        user = authenticate(email=email, password=password)
        if user is not None:
            if user.is_active:
               login(request, user)
               user_info=Person.objects.filter(user=request.user)
               print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$7777",user_info.name)

               return render(request, 'display_info.html', {'details':user_info,'name':user_info.name})
            else:
                return render(request, 'home.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'home.html', {'error_message': 'Invalid login'})
    return render(request,'home.html',{})





def check_new(request):
    return render(request,'add_image.html',{})

def check_new2(request):
    form=image_data
    dis="HEALTHY!!"
    tret="HEALTHY!!"
    acc=""
    acc=0

    mail=Person.objects.filter(user=request.user).values()[0]['email']
    if request.method == 'POST':
        form = image_data(request.POST, request.FILES)
        
        
        if form.is_valid():
            img = Image.open(form.cleaned_data['photo'])
            print(img)
            img.save("detect/pic.jpg")
            #exec(open("mach/sn.py").read())
            #file_globals = runpy.run_path("mach/sn.py")
            #execfile("mach/sn.py")
            dis,tret,acc=sn.openphoto()

            f=open("num.txt","r")
            if f is not None:
                print("opened successfully")
            
            idd=f.read()
            print("&&&&&&&&&&&&&&&8",idd)
            f.close()
            f=open("num.txt","w")
            f.write(str(int(idd)+1))
            f.close()

            a=photo_data(id=idd ,email1=mail,disease=dis,suggestion=tret,photo=form.cleaned_data['photo'] )
            print("TTTTTTTTTTTTTTTTTTTTT",form.cleaned_data['photo'])
            a.save()
            #form.save()
            return render(request,'result.html',{'a':a,'acc':acc})
    else:
        form = image_data()
    return render(request, 'add_image.html', {
        'form': form
    })











"""
    form=image_data
    #print(request.Method)
    if request.method=="POST":
        form=image_data(request.POST)
        if form.is_valid():
            user=request.user
            photo=request.FILES.get('myfile')
            person=Person.objects.filter(user=user)
            email1=person.values()[0]['email']
            disease="LIGHTBLIGHT"
            suggestion="TREATITNOW"
            a=photo_data.objects.create(email1=email1,disease=disease,suggestion=suggestion,photo=photo)
            return render(request,'result.html',{'photo_data':a})
    return render(request,'empty.html',{})"""






def check_old(request):
    person2=Person.objects.filter(user=request.user)
    print("&&&&&&&&&&&&&&&&&&&&&&&&&&7",person2.values()[0]['email'])
    image_data=photo_data.objects.filter(email1=person2.values()[0]['email'])
    if image_data :
        print("HEYYYYYYYYYYYY")
        return render(request,'display_photo.html',{'data':image_data})
    return render(request,'empty.html',{})

def delete_pics(request):
    person2=Person.objects.filter(user=request.user)
    print("&&&&&&&&&&&&&&&&&&&&&&&&&&7",person2.values()[0]['email'])
    image_data=photo_data.objects.filter(email1=person2.values()[0]['email'])
    image_data.delete()
    return render(request, 'display_info.html', {'details':person2,'name':person2.values()[0]['name']})


def about(request):
    return render(request,'about.html',{})


def register(request):
    title="ADD USER"
    form = RegistrationFormUser
    print("@@@@@@@@@@@@@@@@",request.method)
    if request.method=="POST":
        form=RegistrationFormUser(request.POST)
        if form.is_valid():

            name=form.cleaned_data['name']
            email=form.cleaned_data['email']
            address=form.cleaned_data['address']
            age=form.cleaned_data['age']
            gender=form.cleaned_data['gender']
            profession=form.cleaned_data['profession']

            user=get_user_model().objects.create_user(form.cleaned_data['email'],form.cleaned_data['email'],form.cleaned_data['password'])
            user.save()
            Person.objects.create(user=user,name=name,email=email,address=address,age=age,gender=gender,profession=profession)

            message = "New USER is added"
            return render(request, 'stuff_added.html', {'display_text': message})

    return render(request, 'register.html', {'form': form, 'title': title})

website/farming/templates/about.html
{% extends "home.html" %}
{% block title %}About Us{% endblock %}

{% block body %}

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
    body {
      font-family: Arial, Helvetica, sans-serif;
      margin: 0;
    }
    
    html {
      box-sizing: border-box;
    }
    
    *, *:before, *:after {
      box-sizing: inherit;
    }
    
    .column {
      float: left;
      width: 33.3%;
      margin-bottom: 16px;
      padding: 0 8px;
    }
    
    .card {
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
      margin: 8px;
    }
    
    .about-section {
      padding: 50px;
      text-align: center;
      background-color: #586174;
      color: white;
    }
    
    .container {
      padding: 0 16px;
    }
    
    .container::after, .row::after {
      content: "";
      clear: both;
      display: table;
    }
    
    .title {
      color: grey;
    }
    
    .button {
      border: none;
      outline: 0;
      display: inline-block;
      padding: 8px;
      color: white;
      background-color: #000;
      text-align: center;
      cursor: pointer;
      width: 100%;
    }
    
    .button:hover {
      background-color: #555;
    }
    .h2 {
        font-size: 600%;
    }
    
    @media screen and (max-width: 650px) {
      .column {
        width: 100%;
        display: block;
      }
    }
    </style>
    <body>
    <br>
    <br>
    <br>
    <div class="about-section">
      <h2>About Us</h2>
    </div>
    <br><br>
    <div class="row">
      <div class="column">
        <div class="card">
          <img src="../static/farming/images/WhatsApp Image 2020-08-16 at 13.23.04.jpeg" alt="" height="350px" width="300px">
          <div class="container">
            <h2>Jagdeep Singh</h2>
            <p>jagdeep2620@gmail.com</p>
            <p>+91-797-359-4553</p>
          </div>
        </div>
      </div>
    
      <div class="column">
        <div class="card">
          <img src="../static/farming/images/piyush.jpg" alt="" height="350px" width="300px">
          <div class="container">
            <h2>Piyush Chechi</h2>
            <p>chechipiyush@gmail.com</p>
            <p>+91-870-818-5501</p>
          </div>
        </div>
      </div>
      
      <div class="column">
        <div class="card">
          <img src="../static/farming/images/WhatsApp Image 2020-08-16 at 13.31.16.jpeg" alt="" height="350px" width="300px">
          <div class="container">
            <h2>Anmol Kumar</h2>
            <p>anmolpunia9@gmail.com</p>
            <p>+91-798-849-8936</p>
          </div>
        </div>
      </div>
    </div>
    
    </body>


{% endblock %}

website/farming/templates/add_image.html
{% extends "home.html" %}

{% block title %}CHECK IMAGE{% endblock %}


{% block body %}
 
    <form method = "post" enctype="multipart/form-data"> 
        {% csrf_token %} 
        {{ form.as_p }} 
        <button type="submit" href="{% url 'farming:check_new2' %}">Upload</button> 
    </form> 

{% endblock %}

website/farming/templates/display_info.html
{% extends "home.html" %}
{% block title %}Welcome {{name}}{% endblock %}

{% block body %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<table class="w3-table-all w3-xxlarge">
    <tr>
        <th>Name </th>
        <th>Email </th>
        <th>Address </th>
        <th>Age  </th>
        <th>Profession </th>
    </tr>
    <tr>
    <a>{% for s in details %}
      <td>{{s.name}}</td>
      <td>{{s.email}}</td>
      <td>{{s.address}}</td>
      <td>{{s.age}}</td>
      <td>{{s.profession}}</td>
    {%endfor%}</a>
    </tr>
    </table>
    <div class="container-fluid">
<br>
<br>
<br>

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<div class="row">
            <div class="col-sm-12 col-md-6">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <body>
                            <form >
                                <a class="w3-button w3-border w3-xlarge" href="{% url 'farming:check_new2' %}">To Check a new Image  </a>
                                <a class="w3-button w3-border w3-xlarge" href="{% url 'farming:check_old' %}">  To See previously checked Images  </a>
    
                            </form>
                        </body>    
                    </div>
                </div>
            </div>
        </div>
    
    </div>
    
{% endblock %}

website/farming/templates/display_photo.html
{% extends "home.html" %}
{% block title %}Welcome {{name}}{% endblock %}


<meta name="viewport" content="width=device-width, initial-scale=1">

<div class="parallax"></div>

<div class="parallax-container">


  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=5">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </head>
   


{% block body %}
<div class="container p-3 my-3 bg-primary text-black" >

 
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <div class="row">
  <div class="col-sm-12 col-md-6">
    <div class="panel panel-default" >
        <div class="panel-body">
            <a class="w3-button w3-border w3-xlarge" href="{% url 'farming:delete_pics' %}">To delete all Images  </a>
        </div>
    </div>
  </div>
  </div>
<br>
<p1>{% for s in data%}
      <p>Disease: {{s.disease}}</p>
      <p>Treatment: {{s.suggestion}}</p>
      <br>
      <img src="{{s.photo.url}} "  /> 
      <br><br>
 {% endfor %} </p1>


</div>


{% endblock %}

website/farming/templates/empty.html
{% extends "home.html" %}
{% block title %}Welcome {{name}}{% endblock %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

{% block body %}
<div class="w3-container"> 
  
    <h2>"NOTHING TO DISPLAY"</h2>
  </div>
  

{% endblock %}

website/farming/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}FARMING{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="../static/farming/leaf_6-256.png"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="../static/farming/style.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<r class="parallax-wrapper">
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'farming:home' %}">Farming</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'farming:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'farming:login1' %}">Log In</a></li>
                <li class="{% block about_active %}{% endblock %}"><a href="{% url 'farming:about' %}">About Us</a></li>
            </ul>
        </div>

    </div>

</nav>

{% block body %}

<style>
    h1 {
      text-shadow: 0 0 1px #224758, 0 0 5px #dd0d0d;
    
      text-align: center;
      font-size: 600%;
    }
    </style>
      <h1>WELCOME TO</h1>
      <br>
      <h1>CROP-EX</h1>
    <div class="verticalhorizontal">
      <img src="../static/farming/source.gif" width="925px" height="400px" />
    </div>
    <div class="verticalhorizontal2">
        <img src="../static/farming/source.gif" width="925px" height="400px" />
    </div>
{% endblock %}
</body>
</r>
</html>

website/farming/templates/register.html
{% extends 'home.html' %}

{% block title %}Register User{% endblock %}
{% block register_active %}active{% endblock %}

{% load crispy_forms_tags %}

{% block body %}
<centre>
<h2>{{title}}</h2>
<form method="post" novalidate>
    {% csrf_token %}
      {% if messages %}
          {% for message in messages %}
            <div class="alert alert-success">
                {{ message }}
            </div>
          {% endfor %}
      {% endif %}
  
      
      {{ form|crispy }}
    <button type="submit" class="btn btn-primary" >Submit</button>
          </form>
</centre>
{% endblock %}

website/farming/templates/result.html
{% extends "home.html" %}

{% block title %}RESULTS{% endblock %}


{% block body %}

<style>
    a2 {
      width: 100px;
      padding: 0px;
      border: 5px solid gray;
      margin: 0;
      color: #0e0d0d ;
      font-size: 150%;
      background-color: rgb(233, 238, 243);
    }
    </style>
<div > 
    <a2>DISEASE:  {{a.disease}} </a2>
    <a2>SUGGESTION:  {{a.suggestion}} </a2>
    <a2> {{acc}} </a2>

    <br>
    <img src="{{a.photo.url}}" />
</div>
{% endblock %}

website/farming/templates/stuff_added.html
{% extends "home.html" %}

{% block title %}{% endblock %}


{% block body %}


<h1>{{display_text}}</h1>


{% endblock %}